### ISSUE TITLE
Error while creating basic Packer image creation " Unknown configuration key = "ämi-name"

### ISSUE THREAD

**Issue by SuneelkumaarNarayana** [QT-DevOps/DevOpsIssues#184]
Can anybody help on this please.

Error while creating basic Packer image creation " Unknown configuration key = "ämi-name"

Screenshot below:

![image](https://user-images.githubusercontent.com/42944285/45994402-15a9e400-c0b1-11e8-8017-ef5649b685f2.png)

**Comment by arunkumar127** [comment]
@SuneelkumaarNarayana 
You're trying to create amazon-ebsvolume, which won't have key ami_name
Check document - https://www.packer.io/docs/builders/amazon-ebsvolume.html

Instead of ebsvolume, use ebs "type":"amazon-ebs".
Then your code will work.
EBS Document - https://www.packer.io/docs/builders/amazon-ebs.html

**Comment by revathi-muthana123** [comment]
yes, "type" must be "amazon-ebs"

**Comment by SuneelkumaarNarayana** [comment]
Thanks a lot. It worked.
