### ISSUE TITLE
Displaying ShemGen issue while running docker command

### ISSUE THREAD

**Issue by SajidAliKhanMohammed** [QT-DevOps/DevOpsIssues#208]
Hi Friends
I am facing the issue of ShemGen error while running docker command "docker run -p 8080:8080 -p 50000:50000 jenkins" (see screenshot). I even installed docker temporarily thru choco, and tried to execute the above command.
Is this because any .exe file got corrupted in chocolatey ? Do i need to uninstall and reinstall chocolatey ?
Please suggest..
![shemgen-issue](https://user-images.githubusercontent.com/16450606/46582292-ece6fe80-ca61-11e8-85b6-a225e9f1f226.png)

Thanks
SajidKhan

**Comment by raviops100** [comment]
Hi Sajid,

As per my knowledge it is not related docker issue

Shim has stooped working : Related to Your OS and Antivirus related Issue

if you have received this error on your PC,
it means there is was a mal function in your system operation 
common reasons include 
incorrect failed installation or un installation that may left entries in windows registry
virus(or) malware attack mprored shutdown due to power failure.

Thanks
Ravi

**Comment by SajidAliKhanMohammed** [comment]
Hi Ravi

If it the issue which you mentioned above, then what all I need to do ? If a windows repair can solve my problem because i am completely blocked with this issue.

Thanks
SajidKhan

**Comment by shaikkhajaibrahim** [comment]
Please use windows 10/ Linux for docker
