### ISSUE TITLE
kubernetes-kubeadm join failure from node

### ISSUE THREAD

**Issue by shivakumarkokomuravelly** [QT-DevOps/DevOpsIssues#234]
Hi,
i unable to connect from node  i got the error while i joining from node. iam  doing it from virtual box using vagrant(ubuntu 16)

![image](https://user-images.githubusercontent.com/40332104/47356698-6c233600-d6e2-11e8-9ad2-2f1f9da2476a.png)

thnks
Hari.m

**Comment by raviops100** [comment]
HI SHIVAKUMAR,

Can you please fallow issue number 237 your issue is also similar
i have given few installation steps in 237 issue  just try to execute the commands

SUGGETION:

Plase donot use Kubernates installation in vagrant ubuntu

Better Try to Launch AWS EC2 instance ubuntu 16.04 (or) CentOS6

Any how if you take Vagrant ubuntu VM also it should work 
For safeside go for AWS instance

Thanks
Ravi

**Comment by revathi-muthana123** [comment]
I think you have to open ports in ubuntu machine.
pls refer : https://www.digitalocean.com/community/tutorials/how-to-set-up-a-firewall-with-ufw-on-ubuntu-16-04

**Comment by raviops100** [comment]
Hi is this issue resolved ???

**Comment by shivakumarkokomuravelly** [comment]
No

**Comment by raviops100** [comment]
Are you trying to install on Kubernates from vagrant ubuntu
or
machine launched in AWS and trying to install kubernates ???

**Comment by shaikkhajaibrahim** [comment]
Is  this resolved??
