### ISSUE TITLE
error while executing Start-DscConfiguration in powershell Dsc

### ISSUE THREAD

**Issue by harimakenti** [QT-DevOps/DevOpsIssues#258]
The client cannot connect to the destination specified in the request. Verify that the service on the destination is
running and is accepting requests. Consult the logs and documentation for the WS-Management service running on the
destination, most commonly IIS or WinRM. If the destination is the WinRM service, run the following command on the
destination to analyze and configure the WinRM service: "winrm quickconfig".
    + CategoryInfo          : ConnectionError: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : HRESULT 0x80338012
    + PSComputerName        : localhost

**Comment by revathi-muthana123** [comment]
Hi,
Pls follow this documentation.
URL: https://winaero.com/blog/change-powershell-execution-policy-windows-10/
After that "Enable PSRemoting", Then try to execute.

Thanks & Regards
Revathi

**Comment by Santosh-Peddada** [comment]
Hi
I have followed the doc and tried "Enable PSRemoting" and end up with below error
Enable-PSRemoting
WinRM is already set up to receive requests on this computer.
Set-WSManQuickConfig : <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="localhost"><f:Message><f:ProviderFault provider="Config
provider" path="%systemroot%\system32\WsmSvc.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="DESKTOP-LOU7JB1"><f:Message>WinRM
firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again.
</f:Message></f:WSManFault></f:ProviderFault></f:Message></f:WSManFault>
At line:116 char:17
+                 Set-WSManQuickConfig -force
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-WSManQuickConfig], InvalidOperationException
    + FullyQualifiedErrorId : WsManError,Microsoft.WSMan.Management.SetWSManQuickConfigCommand

Set-WSManQuickConfig -force
WinRM is already set up to receive requests on this computer.
Set-WSManQuickConfig : <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="localhost"><f:Message><f:ProviderFault provider="Config
provider" path="%systemroot%\system32\WsmSvc.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="DESKTOP-LOU7JB1"><f:Message>WinRM
firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again.
</f:Message></f:WSManFault></f:ProviderFault></f:Message></f:WSManFault>
At line:1 char:1
+ Set-WSManQuickConfig -force
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Set-WSManQuickConfig], InvalidOperationException
    + FullyQualifiedErrorId : WsManError,Microsoft.WSMan.Management.SetWSManQuickConfigCommand

**Comment by revathi-muthana123** [comment]
> Hi
> I have followed the doc and tried "Enable PSRemoting" and end up with below error
> Enable-PSRemoting
> WinRM is already set up to receive requests on this computer.
> Set-WSManQuickConfig : <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="localhost"><f:Message><f:ProviderFault provider="Config
> provider" path="%systemroot%\system32\WsmSvc.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="DESKTOP-LOU7JB1"><f:Message>WinRM
> firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again.
> </f:Message></f:WSManFault></f:ProviderFault></f:Message></f:WSManFault>
> At line:116 char:17
> 
> * ```
>               Set-WSManQuickConfig -force
>   ```
> * ```
>               ~~~~~~~~~~~~~~~~~~~~~~~~~~~
>   ```
>   
>   * CategoryInfo          : InvalidOperation: (:) [Set-WSManQuickConfig], InvalidOperationException
>   * FullyQualifiedErrorId : WsManError,Microsoft.WSMan.Management.SetWSManQuickConfigCommand
> 
> Set-WSManQuickConfig -force
> WinRM is already set up to receive requests on this computer.
> Set-WSManQuickConfig : <f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="localhost"><f:Message><f:ProviderFault provider="Config
> provider" path="%systemroot%\system32\WsmSvc.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150859113" Machine="DESKTOP-LOU7JB1"><f:Message>WinRM
> firewall exception will not work since one of the network connection types on this machine is set to Public. Change the network connection type to either Domain or Private and try again.
> </f:Message></f:WSManFault></f:ProviderFault></f:Message></f:WSManFault>
> At line:1 char:1
> 
> * Set-WSManQuickConfig -force
> * ```
>     + CategoryInfo          : InvalidOperation: (:) [Set-WSManQuickConfig], InvalidOperationException
>     + FullyQualifiedErrorId : WsManError,Microsoft.WSMan.Management.SetWSManQuickConfigCommand
>   ```

Try with this command "Enable-PSRemoting -SkipNetworkProfileCheck".By using "SkipNetworkProfileCheck" switch of Enable-PSRemoting or Set-WSManQuickConfig you can still allow connections to your computer but those connections must come from other machines on the same subnet.

**Comment by shaikkhajaibrahim** [comment]
I had asked you to try the stuff on Windows 10 EE. What abt the results?
