### ISSUE TITLE
SOURCE IP's and their Frequency

### ISSUE THREAD

**Issue by kishorevunna** [QT-DevOps/DevOpsIssues#413]
Hello Khaja Sir, Thanks for speaking to me on the phone regarding the below issue on Saturday. my company has an e-commerce website, currently running in AWS Cloud with two EC2 Instances, When the website is getting spiked by many number of users especially for the last 3 Sunday's, AWS autoscaling group have triggered and increased to 4 and it has put a tremendous pressure on the database then we doubled the size the database in AWS whereas it is costing too much for the organisation. 

NOTE:
Question1:   my company wants to know who are the frequent users trying to get into the website from the AWS Cloudwatch logs
Question2: we need to know the HOST IP's responsible from the AWS Cloudwatch logs

**Comment by sunil3456** [comment]
ELB with auto scaling gives clients ipaddress logs
Instead of doubling DB use read replicas
if you want specific clients actions go for cloudtrail
please calculate pricing and compare with this usage.

https://www.google.com.au/amp/s/www.codebyamir.com/blog/configure-tomcat-logging-behind-load-balancer%3fformat=amp

**Comment by anon-42** [comment]
You can create a vpc flow logs and find the source ip's from that logs ,in cloudwatch logs, this may solve two of your questions 
https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html
