### ISSUE TITLE
Error while setting java path on ubuntu

### ISSUE THREAD

**Issue by chintalamadhu** [QT-DevOps/DevOpsIssues#431]
Hi, i installed openjdk & maven on ubuntu instance. I set environmental variables for both on ubuntu. But again it is throughing error as "JAVA_HOME" path not available.

Can anyone help me on this?
Please note the attachment.
![error](https://user-images.githubusercontent.com/50047004/57178384-c6206780-6e8c-11e9-8639-614ed613ce83.png)

Thanks,
madhu

**Comment by bhaskardegala** [comment]
Path of java was
JAVA_HOME="/usr/lib/jvm/java-11-oracle/ "
This is for java-11
But better use java-8 instead of java-11 as Jenkins and maven are stable with java-8
If you install java-8 the path will somehow look like
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/"

**Comment by sandhyadev** [comment]
install java-8-openjdk and set java path.
JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64/"

**Comment by revathi-muthana123** [comment]
hi madhu,
Please set environmental variables.

sudo vi /etc/profile

export JAVA_HOME="/usr/lib/jvm/java-11-oracle"
export PATH=JAVA_HOME/bin:$PATH
export M2_HOME="/usr/share/maven"
export PATH=M2_HOME/bin:$PATH

source /etc/profile
java-11 also working fine

**Comment by bhaskardegala** [comment]
> hi madhu,
> Please set environmental variables.
> 
> sudo vi /etc/profile
> 
> export JAVA_HOME="/usr/lib/jvm/java-11-oracle"
> export PATH=JAVA_HOME/bin:$PATH
> export M2_HOME="/usr/share/maven"
> export PATH=M2_HOME/bin:$PATH
> 
> source /etc/profile
> java-11 also working fine

I think for Ubuntu we use environment rather than profile and we use profile for redhat and CentOS for setting environmental variables and from class room discussion I came to know that java-8 was the stable version for jenkins rather than java-11

And for setting maven environment we use

sudo vi /etc/profile.d/mavenenv.sh

export JAVA_HOME="/usr/lib/jvm/java-11-oracle"
export PATH=JAVA_HOME/bin:$PATH
export M2_HOME="/usr/share/maven"
export PATH=M2_HOME/bin:$PATH

Source /etc/profile.d/mavenenv.sh

**Comment by chintalamadhu** [comment]
thank you all, now it is showing mvn version.
