### ISSUE TITLE
Jenkins Build issue - Java compatibility 

### ISSUE THREAD

**Issue by Karthick-Gopalakrishnan** [QT-DevOps/DevOpsIssues#435]
hello Team,

Am building a project from below link 

```
https://github.com/st-tu-dresden/guestbook.git
```
It requires java 11 for packaging... I have installed java 11 and built is manually it worked without issue .

Am trying it through jenkins and it fails saying **invalid target release: 11**

```
[Console output.txt](https://github.com/QT-DevOps/DevOpsIssues/files/3147712/Console.output.txt)
```
salve node is used to build the project where it has two java versions and i have invoked java 11 during Jenkins build 
```
![image](https://user-images.githubusercontent.com/48745218/57223011-b2ecd380-7015-11e9-9677-5886a08fc508.png)

```
```
![image](https://user-images.githubusercontent.com/48745218/57222890-54275a00-7015-11e9-99f4-232f4ea0cb90.png)
```
what am i missing here ?!

**Comment by Karthick-Gopalakrishnan** [comment]
update : when i use mvn package build was successful but when i invoke maven agent the build fails due to java compatibility  

![image](https://user-images.githubusercontent.com/48745218/57223583-981b5e80-7017-11e9-9e33-6c4d6c0173d1.png)

**Comment by bhaskardegala** [comment]
First of all I was not able to Access your files that you have mentioned and by seeing at the error I think the possible chance for this failure is Jenkins is not completely compatible with java 11 when it is trying to speak with node and plugins may fail to speak due to compatible issue for best practice it is better to use invoke shell when java version is other than 8, if you need some more details please check this [link](https://support.cloudbees.com/hc/en-us/articles/360020783632-Java-compatibility-Apache-Maven-and-Jenkins-Best-Practices?mobile_site=true) it can help you to know the compatible versions in detail

**Comment by Karthick-Gopalakrishnan** [comment]
Bhaskar, 

Thanks for taking your time to reply. Will close the issue
