### ISSUE TITLE
i got error while creating packer image 

### ISSUE THREAD

**Issue by murali3352** [QT-DevOps/DevOpsIssues#455]
![issue 2](https://user-images.githubusercontent.com/50665579/57777677-05c63980-7740-11e9-8926-7af45911466d.PNG)
Script exited with non-zero exit status: 100.Allowed exit codes are: [0]
Builds finished but no artifacts were created.
![issue](https://user-images.githubusercontent.com/50665579/57777507-bb44bd00-773f-11e9-9bb2-cae9e02c3da5.PNG)

**Comment by bhaskardegala** [comment]
If you are variables from variable file you must use jinga templating, example
"source_ami":"{{user 'my_access_key'}}"
Use ` Instead of ' in above statement

**Comment by dharmatejadevops** [comment]
> If you are variables from variable file you must use jinga templating, example
> "source_ami":"{{user 'my_access_key'}}"
> Use ` Instead of ' in above statement

"source_ami":"{{user 'my_access_key'}}" not single codes['] here using this symbols  `
like showing bellow image
![Capturesym](https://user-images.githubusercontent.com/43385451/57790863-39618d80-7759-11e9-8d9f-a938a9ef1e89.PNG)

 like this you can pass all variables in above template.

**Comment by Meganathreddy** [comment]
Hello Murali, Even i faced the same issue. However, in my case it was due to the error "unable to locate package tree". As, tree package was not present in Amazon_ubuntu machine. So i have removed "sudo apt-get install tree -y" from the script and tried again. now the issue is resolved. 

We can help you if you can show us the exact error message which you faced, because in the above screenshot provided by you there is no information related to error messages.

Please find the below screenshot where you can see the error message.
![Error_Image Creation_Packer](https://user-images.githubusercontent.com/39144078/57872714-ea375d80-7829-11e9-91e5-c51dce65abb1.PNG)

hope this helps you..
![image](https://user-images.githubusercontent.com/39144078/57873219-333be180-782b-11e9-9270-1e292665050e.png)

**Comment by ghost** [comment]
hello, murali


> > If you are variables from variable file you must use jinga templating, example
> > "source_ami":"{{user 'my_access_key'}}"
> > Use ` Instead of ' in above statement
> 
> "source_ami":"{{user 'my_access_key'}}" not single codes['] here using this symbols `
> like showing bellow image
> ![Capturesym](https://user-images.githubusercontent.com/43385451/57790863-39618d80-7759-11e9-8d9f-a938a9ef1e89.PNG)
> 
> like this you can pass all variables in above template.
hello murali please do like above 
this definetly work please do and close issue

**Comment by murali3352** [comment]
> Hello Murali, Even i faced the same issue. However, in my case it was due to the error "unable to locate package tree". As, tree package was not present in Amazon_ubuntu machine. So i have removed "sudo apt-get install tree -y" from the script and tried again. now the issue is resolved.
> 
> We can help you if you can show us the exact error message which you faced, because in the above screenshot provided by you there is no information related to error messages.
> 
> Please find the below screenshot where you can see the error message.
> ![Error_Image Creation_Packer](https://user-images.githubusercontent.com/39144078/57872714-ea375d80-7829-11e9-91e5-c51dce65abb1.PNG)
> 
> hope this helps you..
> ![image](https://user-images.githubusercontent.com/39144078/57873219-333be180-782b-11e9-9270-1e292665050e.png)

Hello meganathreddy, Its works for me thank you.
 I'm also facing with "**unable to locate package tree** ". I don't know why it happens to this code, after that I created images using tree I didn't get any issues regarding **unable to locate package tree**
Once again thank you all
Thank you for your response
