### ISSUE TITLE
Please find the screen shot below. I am getting this error in master while  following the doc

### ISSUE THREAD

**Issue by hanocc** [QT-DevOps/DevOpsIssues#507]
![Capture1223](https://user-images.githubusercontent.com/51271895/59902330-90731600-941b-11e9-9144-0337db5e1321.PNG)

**Comment by bhaskardegala** [comment]
I think you have already initiated it before

**Comment by bhaskardegala** [comment]
You can even reset this by following command
Kubeadm reset --help
Use arguments that can help you

**Comment by sandhyadev** [comment]
The reason that it mentions the port is in use is because you already ran kubeadm init once and it has already changed a number of things.
run "kubeadm reset" first to undo all of the changes from the first time you ran it.
Then run "systemctl restart kubelet"
Finally, when you run kubeadm init you should no longer get the error.
I Think you understood hanocc.

**Comment by hanocc** [comment]
Thanks Sandhya, please tell me the command to run...

**Comment by hanocc** [comment]
Hi Sandhya,

From where I need to run this commad
Inside sudo -i or sudo usermod -aG?

**Comment by sandhyadev** [comment]
"kubeadm reset [Options]"-this command to getbacks any changes made by 'kubeadm init' or 'kubeadm join' commands.
I think it works but not sure because etcd store all details:
"kubeadm reset phase remove-etcd-member" 
and run it as root user to avoid permission issues

**Comment by hanocc** [comment]
Thanks, I'll check it out.

**Comment by bhaskardegala** [comment]
Hope your issue was been resolved if yes please close the issue
