### ISSUE TITLE
Docker issue

### ISSUE THREAD

**Issue by sunnydevops** [QT-DevOps/DevOpsIssues#580]
When I am trying to run a docker command it's giving me a "Segmentation fault" issue.

$ docker ps
Segmentation fault

**Comment by ghost** [comment]
please share logs

**Comment by raviops99** [comment]
Hi sunny, 
Can you please execute below commands
Docker stop $(docker PS -a - q) 
docker rmi $ (docker images -q) 
The try docker ps

**Comment by satish225** [comment]
This issue might be related to memory full,bcz of multiple containers are running on same host , if you are using amazon go for more than 1G Ram bcz of this issue you are facing issues..remove your existing containers using docker rm -f $(docker ps -aq) and try to run containers again so that u can avoid this memory issues
