### ISSUE TITLE
docker path

### ISSUE THREAD

**Issue by NarendarBabu** [QT-DevOps/DevOpsIssues#623]
[node1] (local) root@192.168.0.18 ~/docker
$ docker build -t fdoc .
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /root/docker/Dockerfile: no suc
h file or directory
[node1] (local) root@192.168.0.18 ~/docker
$ 

i have created the path in windows D:\ drive from there i have opened studio and created the file as docker

this is exact path
D:\QT-DEVOPS\devops\sep19\docker

**Comment by satish225** [comment]
If you are building docker images please provide the exact path where docker file is created so that u can avoid such issues and docker file must be like this (Dockerfile)

**Comment by kishoregudidha** [comment]
Hi NarendarBabu,

Please look into my comments so that you can understand what did you do wrong.

Step 1: You are running docker build command from  "/root/docker/Dockerfile" , But your file is located under "D:\QT-DEVOPS\devops\sep19\docker "

**[node1] (local) root@192.168.0.18 ~/docker**
$ docker build -t fdoc .

Step 2: Go to D:\QT-DEVOPS\devops\sep19\docker path and execute "docker build -t fdoc ."

If not execute like docker build -t fdoc  D:\QT-DEVOPS\devops\sep19\docker 

Thanks,

Kishore.G

**Comment by bhaskardegala** [comment]
Hi Nagendra

As sathish and Kishore explained make sure that you name your file as Dockerfile rather than docker and make sure this file is present from where you are running this command , hope your issue was resolved please update accordingly and close the issue

**Comment by NarendarBabu** [comment]
I missed the vi dockerfile to create and write steps...
thats the error about. Nothing on the path and Path was very much perfect.
