### ISSUE TITLE
how to recover forgot password in linux

### ISSUE THREAD

**Issue by chowdamramana** [QT-DevOps/DevOpsIssues#629]

**Comment by Jsuresh47** [comment]
https://www.maketecheasier.com/reset-root-password-linux/

it may use for you.

**Comment by chowdamramana** [comment]
> https://www.maketecheasier.com/reset-root-password-linux/
> 
> it may use for you.

thanks , but I want the process for ubuntu server not for desktop

**Comment by srmanikanta** [comment]
To change regular user password itself follow 
#passwd ->command if will ask current and new password for change
or
To change any regular user password as ROOT
Root user can change any regular user password #password <username>
This time current password is not asked for that ueser because Root user have all the permissions
or 
you can set a forgotten password of  root user follow the below link
https://www.cyberciti.biz/faq/linux-reset-forgotten-root-password/

**Comment by raviops99** [comment]
please close the issue
