### ISSUE TITLE
 Error response from daemon: OCI runtime create failed

### ISSUE THREAD

**Issue by tulasikanna** [QT-DevOps/DevOpsIssues#641]
Hi there ,
       am using ubuntu 14.04 system and i installed docker successfully. But the problem comes from when am  creating a docker container. i con't find what exactly this error ! is that memory issue ?
  
**docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "process_linux.go:297: copying bootstrap data to pipe caused \"write init-p: broken pipe\"": unknown.**

please anyone help me  what sort of error is this ? thanks in advance

**Comment by raviops99** [comment]
Hi Tulasi,
To resolve this errors we have 2 ways
1. It is related ubuntu Linux kernel version issue with docker
Please try below commands
sudo apt-get install linux-generic-lts-xenial
sudo reboot 
Then login in to machine try create container if you get same issue
2. otherwise please launch ubuntu 16.04 LTS install docker create container
Thanks
Ravi

**Comment by srmanikanta** [comment]
please post a screenshot of your command along with error message

**Comment by shaikkhajaibrahim** [comment]
please use atleast ubuntu 16:04
