### ISSUE TITLE
Issue with Deploy Jar file in Tomcat

### ISSUE THREAD

**Issue by Jsuresh47** [QT-DevOps/DevOpsIssues#647]
Hi, 
How to deploy jar file into Tomcat server.

**Comment by CHARANJAI** [comment]
Hi Suresh,
Greetings!!

If you installed tomcat7 using  apt-get  in linux then, deploy your app to /var/lib/tomcat7/webapps/

Ex:
sudo service tomcat7 stop
mvn clean package
sudo cp
 target/(your).war/var/lib/tomcat7/webapp/

#you might also want to make sure war file has permission (`777` not just `+x`)

sudo service tomcat7 start

Also, keep tailing the tomcat log so that you can verify that your app is actually making peace with tomcat.

tail -f /var/lib/tomcat7/logs/catalina.out

The deployed application should appear in 

  http://172.16.35.155:8080/

Thanks,
Charan Jayee

**Comment by bhaskardegala** [comment]
Hi Suresh

Chiranjeevi shared some good content hope you got that , please update and
close the issue

**Comment by srmanikanta** [comment]
please follow these link
For ubuntu: 
https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-7-on-ubuntu-14-04-via-apt-get
For centos:
https://www.digitalocean.com/community/tutorials/how-to-install-apache-tomcat-7-on-centos-7-via-yum
Note: tomcat version is changed based on the os which you are used.
