### ISSUE TITLE
Password authentication problem for *Chef* Bootstrapping process

### ISSUE THREAD

**Issue by LetsFaceTheAIBro** [QT-DevOps/DevOpsIssues#654]
Hi There,

Gaffoor here....!!

I am trying to execute Knife Bootstrap command prompt for Ubuntu node,

Used: 
" knife bootstrap 3.135.184.5 -U ubuntu -i ./chef/gaffoor.pem --sudo -N ip-172-31-15-139.us-east-2.compute.internal "

Placed 
          .Pem : C:\Practice\Chef\chef-repo
  starter kit : C:\Practice\Chef\chef-repo
        chefdk : C:\Practice 

But asking " Password Authentication ".

Attached SS for reference.

![Chef paasword](https://user-images.githubusercontent.com/46358830/69403560-e593ba80-0d20-11ea-9fbd-190ddde77de4.PNG)

**Comment by bhaskardegala** [comment]
Hi ,
Here it was unable to find your aws machine  pem key file , make sure of
your pem file path or place it in Chef-repo folder and just specify
./xyz.pem , please update the issue accordingly

**Comment by LetsFaceTheAIBro** [comment]
Hi 

but there is a connection timeout issue and SSH connection failed issue.

![Modifid](https://user-images.githubusercontent.com/46358830/69432663-22cb6d00-0d60-11ea-873e-14ac1eb8839d.PNG)

**Comment by bhaskardegala** [comment]
Is 22 port of your node open for all requests

**Comment by srmanikanta** [comment]
you did a mistake in highlighted text please correct with .\chef\gaffoor.pem
because in windows path are seperated by \ (back slash) in linux paths are seperated by / (forward slash)
knife bootstrap 3.135.184.5 -U ubuntu -i  **./chef/gaffoor.pem** --sudo -N ip-172-31-15-139.us-east-2.compute.internal
I thinks this information helpful to you if not please ignore
if you done already please close the issue

**Comment by Abbanapuri** [comment]
please pass node pemfile  with location
knife bootstarp ip --sudo -i pemfile-withlocation -x ubuntu -N name
