### ISSUE TITLE
can we run multiple runlists at a time?

### ISSUE THREAD

**Issue by DasaradhBetha9** [QT-DevOps/DevOpsIssues#660]

**Comment by srmanikanta** [comment]
yes, you can run multiple run-lists at a time on different nodes when the convergence happened  but you can't run multiple run-lists on same node because every node have only  one run-list in that you add your recipes or roles.
even you can add same recipe in multiple times chef doesn't execute those recipes.
I think it is helpful to you, if not please ignore.
if  this question is solved please close the issue.
