### ISSUE TITLE
without notification option i installed lamp stack please check configuration file

### ISSUE THREAD

**Issue by gatkaraju** [QT-DevOps/DevOpsIssues#675]
this is currect or not.
Developing a cookbook for lamp stack

sudo apt-get update
sudo apt-get install apache2 -y
sudo systemctl restart apache2
sudo apt-get install php libapache2-mod-php php-mysql php-cli -y
sudo systemctl restart apache2
sudo nano /var/www/html/info.php
<?php
phpinfo();
?>

sudo systemctl restart apache2

#
# Cookbook:: apachewithphp
# Recipe:: apachephp
#
# Copyright:: 2019, The Authors, All Rights Reserved.

apt_update 'update packages' do
    ignore_failure true
    action :update
end

apt_package 'apache2' do
    action :install
end

apt_package 'php' do
    action :install
end

apt_package 'libapache2-mod-php' do
    action :install
end

apt_package 'php-mysql'  do
    action :install
end

apt_package 'php-cli' do
    action :install
end

remote_file '/var/www/html/info.php' do
    source 'https://gist.github.com/SyntaxC4/5648247/archive/94277156638f9c309f2e36e19bff378ba7364907.zip'
    action :create
end

service 'apache2' do
    action :restart
end

**Comment by srmanikanta** [comment]
Problem with above configuration is every time it restarts the apache2 service if this is a change or not 
if the restart happen automatically the server stop and start means your server have a down time that's why we wrote handlers( notifies in each possibility) whenever the change happen then only it is restarted otherwise there is no change when the convergence happen.

**Comment by srmanikanta** [comment]
please close the issue.
