### ISSUE TITLE
Jenkins: 

### ISSUE THREAD

**Issue by xavyaly** [QT-DevOps/DevOpsIssues#7]
I added plugin "Login with google plugin" post that login stop working and facing the below error:

400. That’s an error.

Error: invalid_request

device_id and device_name are required for private IP: http://<private_ip>:8080/securityRealm/finishLogin

Can you please provide a resolution.

**Comment by shaikkhajaibrahim** [comment]
Did you performed all the steps mentioned here http://www.tothenew.com/blog/jenkins-google-authentication/

Because you need to also add the app to google.

But why google plugin?

Any use case around it . If just for fun. Please raise issues @ https://plugins.jenkins.io/google-login
as the plugins not working haunting jenkins might be plugin usage / plugin issues

**Comment by xavyaly** [comment]
Yes, already followed the steps described here "http://www.tothenew.com/blog/jenkins-google-authentication/".

Google plugin is required because of new implementation.

Actually, it's re-directing to private IP instead of public IP.

**Comment by shaikkhajaibrahim** [comment]
In that case use dns hostname mapping (rather than ip address)

**Comment by shaikkhajaibrahim** [comment]
for example jenkins.mydomain.com
