### ISSUE TITLE
remote-exec provisioner ssh connection false

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#720]
I'm creating a vm and running a remote-exec provisioner.

The logs show that the provisioner tries connecting to the server.but ssh connection failed 
![ssh false](https://user-images.githubusercontent.com/58951038/72886415-cbca2000-3d2f-11ea-939f-ab711a20fd33.PNG)

**Comment by kslvvaraprasad** [comment]
same issue for me also.

**Comment by ABBANAPURI0445** [comment]
check pem file and security group
share tf file

**Comment by ABBANAPURI0445** [comment]
please check vpc (internet gataway and routetable )

**Comment by MakrandakaMax** [comment]
I had the same issue. You maybe creating your own VPC. If that's the case then you need to create many more things, like subnets, route, route tables etc. So instead of creating all these, just to check if my project is working, I just used the default vpc and it worked. Spent like 4 days figuring this out in the Pongal holidays, was over the moon when i finally got the solution.

**Comment by ghost** [comment]
i have figured it out man. we have to give subnet access to route table
