### ISSUE TITLE
ansible -m setup -a issue

### ISSUE THREAD

**Issue by kslvvaraprasad** [QT-DevOps/DevOpsIssues#775]
hi 
  i am using setup command ansible -m setup -a 'filter=*os*' all  on acs .i am getting the error as attached below.
![ansible setup module issue](https://user-images.githubusercontent.com/58965423/77221488-29cc8580-6b70-11ea-986f-cdccc0b5565a.PNG)

 where as in the place of all i am using localhost i am getting output as follows

![ansible setup module issue local host](https://user-images.githubusercontent.com/58965423/77221681-da875480-6b71-11ea-824c-8acfdcbc3e4c.PNG)

**Comment by srmanikanta** [comment]
hi, varaprasad 
`ansible -m setup -a 'filter=*os*' all` 
the above command is working fine for me but you are facing the above error 
because you didn't mention any hosts in /etc/ansible/hosts please check
or if you use another inventory otherthan hosts please mention over there.

if you resolve the issue, please close the issue.

**Comment by kslvvaraprasad** [comment]
thank you manikanta got solution...thanks for your support.
