### ISSUE TITLE
Please have look, Issue while bootstrap

### ISSUE THREAD

**Issue by Jagannath92** [QT-DevOps/DevOpsIssues#798]
![Capture](https://user-images.githubusercontent.com/58015684/79241536-cc86d400-7e90-11ea-98cf-1628aea62da2.PNG)

**Comment by srmanikanta** [comment]
Hi jagannath, 
Chef 15 introduces licensing agreements for commercial applications, which no one anticipated while we were creating this course. Chef 15 is still free for learning purposes though, so you can feel free to experiment with the new versions. To accept the licenses, you can add the "--chef-license accept" option to your bootstrapping command. Let me know if this works for you? Otherwise you can also use the "--bootstrap-version 14" option to force the installation of Chef 14 instead, which doesn't have a license agreement.

**Comment by Jagannath92** [comment]
Thank you Issue solved

**Comment by Jagannath92** [comment]
![Capture1](https://user-images.githubusercontent.com/58015684/79288088-66776c80-7ee3-11ea-933c-56765ba69b58.PNG)

No response for long time and tried two three time bootstrap

**Comment by srmanikanta** [comment]
check these things 
* copy your aws instance pem file to chef-repo
* check the security group(open all or atleast ssh for all) 
* bootstrap command syntax

**Comment by Jagannath92** [comment]
It worked and chef client installed on chef node. But when I try with private ip address I am getting following error
![Capture2](https://user-images.githubusercontent.com/58015684/79626634-2c120780-814f-11ea-8d14-c69e1835f19c.PNG)
