### ISSUE TITLE
error while bootstrap

### ISSUE THREAD

**Issue by pramadhu** [QT-DevOps/DevOpsIssues#799]
error while bootstarp asking ubuntu for password
![fail](https://user-images.githubusercontent.com/58936077/79296214-6c2b7d00-7ef8-11ea-8514-cda6d9fa6b97.png)

**Comment by srmanikanta** [comment]
execute the knife bootstrap command like this 
#knife bootstrap publicip -U username -i .\pemfilename --sudo -N nodename
if it is not working check the connection command like this 
#ping 'instance publinip'
the connection is good no problem otherwise check the security group, and vpc configuration.

**Comment by shaikkhajaibrahim** [comment]
@pramadhu  is this resolved?
