### ISSUE TITLE
Unable to bootstrap chef nodes

### ISSUE THREAD

**Issue by sonu720** [QT-DevOps/DevOpsIssues#818]
![image](https://user-images.githubusercontent.com/59817914/79680888-5d173880-8232-11ea-878b-dd97cccd7277.png)

**Comment by srmanikanta** [comment]
please check that node is already exists or not 
the error messages says it is already exists
if not exists check your security group and first connect that node using git bash, 
now everything is fine it is good to bootstrap.

**Comment by sonu720** [comment]
Node doesn't exist already and security group used is Ssh

**Comment by srmanikanta** [comment]
check the below things:
* check your aws instance pem file is in chef-repo or not
* if exists the pem file then change to chmod 400 <your pemfile> execute this command in gitbash
* check your security group and try to manually using gitbash if connects
* check your os distribution ( ubuntu or centos)
* if your distribution is ubuntu use ubuntu user or your distribution is centos use centos user.
* in you screenshot it says(at the extreme end response) `node already exists` so check all these things.
if this issue is not resolved update the issue.

**Comment by sonu720** [comment]
Hi,
Aws pem file is in chef repo folder
Already tried chmod400 command in gitbash
Changed pem file permissions also
And when I am launching instance I used all traffic

**Comment by srmanikanta** [comment]
call to this number once 7893532934(lab Assistant)

**Comment by sonu720** [comment]
Incoming call are not allowed on that number

**Comment by shaikkhajaibrahim** [comment]
@sonu720  and @srmanikanta  Is the issue resolved

**Comment by sonu720** [comment]
No sir

**Comment by rpkoya** [comment]
HI Sonu,
Please type "knife node list" command and share the result.

**Comment by sonu720** [comment]
[image: image.png]

**Comment by rpkoya** [comment]
Image is missing..

**Comment by sonu720** [comment]
[image: image.png]

**Comment by sonu720** [comment]
![bootstrap](https://user-images.githubusercontent.com/59817914/79965681-f308c880-84a9-11ea-86b9-cc077e965e73.png)

**Comment by rpkoya** [comment]
Hi Sonu,

As per your screenshot, i noticed that your are trying to bootstrap with the same name already exist in your account, please try to give a different name, please find below screenshot for your reference.
![Creating-SameNode](https://user-images.githubusercontent.com/63572053/79976714-b5606b80-84ba-11ea-88e8-80ae88819d20.png)

**Comment by rpkoya** [comment]
HI Sonu,

Is the issue resolved, if yes, please close the issue.
