### ISSUE TITLE
Issue with knife

### ISSUE THREAD

**Issue by manasa373767** [QT-DevOps/DevOpsIssues#819]
Am getting error when i try to use knife commands.Actually i reinsatlled my chefdk and dowloaded again the starter-kit.something got messed up.could anyone resolve this..
![Screenshot (26)](https://user-images.githubusercontent.com/62063357/79689000-bd789b00-826f-11ea-8d12-602fdc4b9bb7.png)
* I also tried by changing the location of starterkit
![Screenshot (25)](https://user-images.githubusercontent.com/62063357/79689047-f284ed80-826f-11ea-8af3-0eb0b7d6dbe1.png)

**Comment by srmanikanta** [comment]
please check these things:
* check your aws instance pem file is in chef-repo or not
* if exists the pem file then change to `chmod 400  <your pemfile>` execute this command in gitbash
* check your security group and try to manually using gitbash if connects
* check your os distribution ( ubuntu or centos) 
* if your distribution is ubuntu use ubuntu user or your distribution is centos use centos user.
if this issue is not resolved update the issue.

**Comment by NareshAbbanapuri** [comment]
Hi
please check pem file and pem file location

**Comment by manasa373767** [comment]
hi team,
its still not working
![1](https://user-images.githubusercontent.com/62063357/79748443-0b9ea480-832b-11ea-953d-e776257c51c9.png)

**Comment by srmanikanta** [comment]
please check you are using a right pem file or not if the key is right one 
change th permissions to read only.
