### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by ghost** [QT-DevOps/DevOpsIssues#83]
Hello Sir,

am unable to login to the aws instance in Git bash

Please help me in solving this and thanks for your time

![screenshot 12](https://user-images.githubusercontent.com/41484533/43643207-21a95d86-9748-11e8-8ead-a2bf89209a5a.png)
![screenshot 13](https://user-images.githubusercontent.com/41484533/43643208-21dc1d48-9748-11e8-8b59-5424ec9cce28.png)
![screenshot 14](https://user-images.githubusercontent.com/41484533/43643209-220c98ba-9748-11e8-8e54-00a3564c6778.png)
![screenshot 15](https://user-images.githubusercontent.com/41484533/43643221-3333e9f4-9748-11e8-8c5c-787c6b2b35a6.png)

**Comment by ghost** [comment]
![screenshot 11](https://user-images.githubusercontent.com/41484533/43643261-58c4b1e4-9748-11e8-8079-dfd3cf3bca59.png)

**Comment by raviops100** [comment]
please try below steps:
 
[EC2-VPC] Check the route table for the subnet. 
You need a route that sends all traffic destined outside the VPC to the internet gateway for the VPC.

In the navigation pane, choose Internet Gateways. Verify that there is an internet gateway attached to your VPC. 
Otherwise, choose Create Internet Gateway to create an internet gateway. 
Select the internet gateway, and then choose Attach to VPC and follow the directions to attach it to your VPC.

**Comment by itzpraveen18** [comment]
AWS from GIT bash  wont run some times due  limit cross age  of Given space better terminate all machines  volumes nd try again it may work again .... same thing i did it worked for me ...... there may other alternatives too better you look into those also

**Comment by Sravan-jk** [comment]
I created the machine with default settings. I changed the region and It worked for me.
Thank you so much
