### ISSUE TITLE
Generic chef question.

### ISSUE THREAD

**Issue by sharmatanmaya** [QT-DevOps/DevOpsIssues#849]
Chef is used for configuration management. I have a generic question to understand. Normally we write chef recipes to install software into the VMs. I believe that is a one time activity. Once after the software is installed, do we need to remove the recipe from the run list of the node? Because it does not make any sense to run those installation recipes again in the same VM.  Because every convergence will run the attached recipes again and again.
Apart from software installation, what other things can be done with configuration management?

**Comment by srmanikanta** [comment]
hi sharmatanmaya,

what is chef:
Chef is an automation tool that provides a way to define infrastructure as code. Infrastructure as code (IAC) simply means that managing infrastructure by writing code (Automating infrastructure) rather than using manual processes. It can also be termed as programmable infrastructure. Chef uses a pure-Ruby, domain-specific language (DSL) for writing system configurations. 

what we will you do in chef 
Below are the types of automation done by Chef, irrespective of the size of infrastructure:
Infrastructure configuration
Application deployment
Configurations are managed across your network

do we need to remove the recipe from the run list of the node?
no need to remove the recipe because chef main idempotence means if you install(or configure) the server using chef it execute the installation only once whether you execute one time or thousand times(except some shell commands).

I think this is useful to you if not please ignore.
