### ISSUE TITLE
Jenkins installation on Ubuntu 14 - works with a slight issue

### ISSUE THREAD

**Issue by rameshm78** [QT-DevOps/DevOpsIssues#85]
Hi,

As instructed, I installed Jenkins Jenkins v1.409.1 on a an Ubuntu 14 machine containing Tomcat 7.
I'm able to view the main page by appending :8080 to the ip address and also able to login to the manager/section, giving the username and password. 

In the Applications table, in the path column, when I click the link /jenkins, I o to another page, which states the following error:
Unable to create the home directory '/usr/share/tomcat7/.jenkins'. This is most likely a permission problem.
To change the home directory, use JENKINS_HOME environment variable or set the JENKINS_HOME system property. See Container-specific documentation for more details of how to do this.

Is this expected or have I made some mistake? 
How to change which permission to fix this issue?

![image](https://user-images.githubusercontent.com/40449948/43649306-70df3c92-975a-11e8-8d2d-86db0821b338.png)

![image](https://user-images.githubusercontent.com/40449948/43649167-0ed7b466-975a-11e8-9ba3-0d7573b69bb3.png)

**Comment by raviops100** [comment]
login in to you machine and execute below steps::

cd /usr/share/tomcat7
sudo mkdir .jenkins
sudo chown -R tomcat7:nogroup .jenkins

=====================================
This directory is where jenkins will be creating workspaces and storing configs for the various projects you will be setting up, 
so it is important that it exists and that jenkins (
or in this case its parent process, tomcat7) has the correct permissions (ie: read, write, execute).

**Comment by rameshm78** [comment]
Thanks a lot Ravi. This worked after I rebooted the EC2 instance after making the change.

Could you please tell me why "nogroup" has been given in the chown command?
When I did ls -l, it showed that the owner of tomcat7 is root.
I'm very new to Linux.

**Comment by raviops100** [comment]
The chown command changes ownership of files and directories in a Linux filesystem.

What is file "ownership"?

Linux is designed to support a large number of users. 
Because of this, it needs to keep careful track of who is allowed to access a file, 
and how they can access it. These access rules are called permissions.

syntax: chown [owner][:[group]] file.

NOGROUP:

nogroup is the group analog to the nobody user. It is used for unprivileged processes 
so that even if something goes wrong the process 
does not have the permissions to cause any serious damage to an important user or group.

**Comment by rameshm78** [comment]
Extremely informative and very important.
Thank you very much.
