### ISSUE TITLE
Jenkins INSTALLATION ISSUE

### ISSUE THREAD

**Issue by Nirupam1705** [QT-DevOps/DevOpsIssues#859]
![Capture](https://user-images.githubusercontent.com/64365617/81574921-0bdb0e80-93c4-11ea-833d-57da7f8d5d9c.PNG)
if i try to install Jenkins and try to check the service status i am getting this issue -- active (exited).

**Comment by srmanikanta** [comment]
I think you launched a t2.micro machine in aws or b1s in azure
if you use aws or azure or any other cloud no problem but take  atleast  `2 cpu's and 4 gb of ram machine`
in aws the required size machine is t2.medium
in azure the required size machine is b2s.

Note: you get this error because the insufficient memory issue.
As I mentioned above please take the machines related to your cloud and try.

**Comment by srmanikanta** [comment]
nirupam if you solve the issue please close the issue.

**Comment by Nirupam1705** [comment]
Thank you

**Comment by srmanikanta** [comment]
hi nirupam call this number once 7893532934.
