### ISSUE TITLE
error while adding node

### ISSUE THREAD

**Issue by mruttala** [QT-DevOps/DevOpsIssues#864]
ERROR: Failed to authenticate as <username>. Wrong password. (credentialId:aws(given this as id)/method:password)

**Comment by srmanikanta** [comment]
hi mruttala,
first connect to jenkins server
1. execute this command from jenkins user `ssh <nodeusername>@<nodeip>`
2. once you connected manually then use these crendential in jenkins node configuration 
the above step is mandatory don't skip this because jenkins server verifies the known_host file
if you manually connected then the entry stored in known_host file otherwise it throws an error.

if you already solve this issue please close the issue.
if you face any issues then update the issue.

**Comment by srmanikanta** [comment]
hi mruttala, are you solve the issue?

**Comment by mruttala** [comment]
Yeah got it..

**Comment by srmanikanta** [comment]
please close the issue.

**Comment by mruttala** [comment]
Ok.
