### ISSUE TITLE
Jenkins login issue when i try to install jenkins in ubuntu --AZURE

### ISSUE THREAD

**Issue by Nirupam1705** [QT-DevOps/DevOpsIssues#865]
I have created a VM in Azure with 8gb Ram and 2vCPU ( standard B2ms).
After installing JAVA and Jenkins i am not able to login to Jenkins portal with public IP using 8080 port number. Please help me in this case.

i have installed Ubutu in my machine and Jenkins worked fine, it is bit sloe because of RAM.

![jenkins](https://user-images.githubusercontent.com/64365617/82088399-4cfa5800-970f-11ea-9df9-9421f826402b.PNG)

My VM
![Jenkins 2](https://user-images.githubusercontent.com/64365617/82088458-6ac7bd00-970f-11ea-8c84-8d03896084c9.PNG)

**Comment by Nirupam1705** [comment]
i had the same issue in AWS cloud too.

**Comment by srmanikanta** [comment]
hi nirupam ,
1. what is the size of the instance you launced, if you launched a t2.micro please change the size of that machine to t2.medium atleast.
2. check the status of the jenkins
3. ensure port 8080 is opened in your security group or not.

**Comment by Nirupam1705** [comment]
i have given the screenshot of my VM.  i have launched my VM im AZURE.
please look at above screenshot

**Comment by srmanikanta** [comment]
nirupam, if you are using azure or aws check the above below things
* create/launch a vm with 2cpu's and 4gb ram.
*  Install  java is isntalled or not
*  then install jenkins
* start the jenkins service, if you already started please check it is running or not( because whenever you stop the vm and start again the service is stopped. so enable the service on every boot
* open port 8080 .

above is the process for any cloud 
the concept of virtaul machine is same in all clouds but the name is vary, if you take azure it is virtual machine, in aws it is ec2 like that for firewall in azure it is network security group, in aws it is security group, so this is the difference remaining all process is same for install the jenkins.

follow the above approach and update the issue.

**Comment by Nirupam1705** [comment]
Thank You Manikanta
