### ISSUE TITLE
chef workbookexercise:1 Manual installation of tellform with Mongodb and Redis on local

### ISSUE THREAD

**Issue by sanjaysureshmv** [QT-DevOps/DevOpsIssues#92]
Hi,

I was trying to manually install tellform on my local machine. As a pre requisite, I have installed Redis and Mongodb and cloned the repo to my local. I am attaching the screenshot of the error I am getting. Is there anything I am missing on the pre requisite part? I have not installed letsencypt, is this is needed for this setup?
![tellform_ssl](https://user-images.githubusercontent.com/39335150/43898764-709b8f0e-9bfd-11e8-8e3f-4084f749917d.png)
When I checked the installation docs, could see installation from Dockerfile. Is this app cant be installed without docker?

**Comment by raviops100** [comment]
Hi Sanjay

i guess in prerequisite part you have miised to install install DNS Masq

1.Redis installed and running at 127.0.0.1:6379
2.MongoDB installed and running at 127.0.0.1:27017 (OR specify the host and port in config/env/all)
3.Also make sure to install DNS Masq or equivalent if running it locally on your computer (look at dns_masq_setup_osx for instructions on OSX)

i guess you have installed above 2 
before executing the any commnd all above three services should be running

for installing DNS Masq Ubuntu 16.04LTS / 14.04LTS below steps

$ sudo mv /usr/sbin/dnsmasq /usr/sbin/dnsmasq.bin
$ sudo curl \
	-o /usr/sbin/dnsmasq \
	https://gist.githubusercontent.com/magnetikonline/6236150/raw/dnsmasq.16.04-14.04.sh
$ sudo chmod a+x /usr/sbin/dnsmasq
# update ETH_INTERFACE to your network interface name

# restart dnsmasq...

# for Ubuntu 16.04LTS
$ sudo systemctl restart NetworkManager

4. you need to install node js in the machine

5. dependencies u need to 
install 
1. npm install
2. bower install
3.grunt build

i have done same thing in ubuntu 16.04 machine i am half-way through i am getting some other error

Last query u have asked docker is not reuired to install this app

but instead of installing all of these for tellform somebody written docker image 

we can use docker image we can install.
if u you follow above steps it may work in your case
if u done above all for the error fs.js: 646 just resinstall npm dependency

**Comment by shaikkhajaibrahim** [comment]
Is it resolved?
